In [1]:
%load_ext autoreload
%autoreload 2

In [10]:
import numpy as np
import pandas as pd
from fuzzywuzzy import process
from constants import DATA_FILENAME, TORVIK_FILE, KENPOM_FILE, ESPN_IDS, ORDER_OF_REGIONS
from scrape_functions import parse_bracket_data, scrape_espn_data

pd.set_option('expand_frame_repr', False)
pd.set_option('display.max_columns', 0)  # Display any number of columns
pd.set_option('display.max_rows', 68)  # Display any number of rows

In [15]:
YEAR = 2026

In [16]:
# This needs to run after the first four games to get the correct names
GENDERS = ["mens", "womens"]
for gender in GENDERS:
    simple = parse_bracket_data(
        scrape_espn_data(id_=ESPN_IDS[YEAR][gender])
    )[['team_name', 'region_id', 'seed']]
    simple['team_region'] = simple['region_id'].apply(
        lambda x: dict(enumerate(ORDER_OF_REGIONS[gender]))[x - 1]
    )
    simple.to_csv(DATA_FILENAME.format(gender=gender), index=False)

# Add KenPom to Mens

In [69]:
kenpom = pd.read_csv(KENPOM_FILE.format(gender="mens"))
team_info = pd.read_csv(DATA_FILENAME.format(gender="mens"))

In [70]:
# Match Kenpom and ESPN team names
kenpom['team_name'] = np.nan
choices = team_info['team_name'].tolist()  # Get all of the ESPN team names
for index, row in kenpom.iterrows():
    team = row['Team']
    match = process.extractOne(team, choices)  # extract the best match for every kenpom name
    if match[1] == 100:  # it's a perfect match
        espn_name = team_info[team_info['team_name'] == match[0]]['team_name'].values[0]
        kenpom.loc[index, 'team_name'] = espn_name
        choices.remove(match[0])  # remove that team as a possible choice

# Need to do this first, otherwise the >80 match ¯\_(ツ)_/¯
kenpom.loc[kenpom['Team'] == "Ohio St.", 'team_name'] = "Ohio State"
choices.remove("Ohio State")
kenpom.loc[kenpom['Team'] == "N.C. State", 'team_name'] = 'North Carolina State'
# choices.remove("North Carolina State")
kenpom.loc[kenpom['Team'] == 'Iowa St.', 'team_name'] = 'Iowa State'
choices.remove('Iowa State')
kenpom.loc[kenpom['Team'] == 'North Dakota St.', 'team_name'] = 'N Dakota St'
choices.remove('N Dakota St')

scores = {}
for index, row in kenpom[kenpom['team_name'].isna()].iterrows():
    team = row['Team']
    match = process.extractOne(team, choices)
    espn_name = team_info[team_info['team_name'] == match[0]]['team_name'].values[0]
    scores[team] = match, espn_name
    if match[1] > 80:
        kenpom.loc[index, 'team_name'] = espn_name
        choices.remove(match[0])  # remove that team as a possible choice

missing_kenpom = kenpom.loc[kenpom['team_name'].isna(), 'Team'].tolist()
missing_espn = team_info.loc[team_info['team_name'].isin(choices)][['team_name']]

print("Missing Kenpom Teams: {}".format(missing_kenpom))
print("Matching ESPN Teams:\n {}".format(missing_espn))

Missing Kenpom Teams: ['Connecticut', 'Texas', 'Miami OH', 'Howard', 'LIU', 'Lehigh', 'Prairie View A&M']
Matching ESPN Teams:
       team_name
5   Long Island
41       PV/LEH
55     TEX/NCSU
60        UConn

In [71]:
scores

{'Connecticut': (('UConn', 72), 'UConn'),
 "St. John's": (("St John's", 95), "St John's"),
 'Utah St.': (('Utah State', 82), 'Utah State'),
 'Miami FL': (('Miami', 90), 'Miami'),
 'Texas': (('TEX/NCSU', 64), 'TEX/NCSU'),
 'SMU': (('M-OH/SMU', 90), 'M-OH/SMU'),
 'Miami OH': (('Long Island', 40), 'Long Island'),
 'Cal Baptist': (('CA Baptist', 95), 'CA Baptist'),
 'Hawaii': (("Hawai'i", 92), "Hawai'i"),
 'UMBC': (('UMBC/HOW', 90), 'UMBC/HOW'),
 'Howard': (('Long Island', 35), 'Long Island'),
 'LIU': (('Long Island', 30), 'Long Island'),
 'Lehigh': (('PV/LEH', 50), 'PV/LEH'),
 'Prairie View A&M': (('PV/LEH', 43), 'PV/LEH')}

In [72]:
# Need to manually fix the crappy ones
# (kenpom_name, espn_name)
manual_matches = [
    ('Connecticut', 'UConn'),
    ('LIU', 'Long Island'),
    # Temp
    ('Lehigh', 'PV/LEH'),
    ('Texas', 'TEX/NCSU'),
    ('SMU', 'M-OH/SMU'),
    ('UMBC', 'UMBC/HOW'),
]
for team, team_id in manual_matches:
    kenpom.loc[kenpom['Team'] == team, 'team_name'] = team_id

merged = kenpom.merge(team_info, left_on=['team_name', 'Seed'], right_on=['team_name', 'seed'])

simple = merged[['team_region', 'Seed', 'team_name', 'AdjustEM', 'AdjustT']]

In [74]:
simple

   team_region  Seed       team_name  AdjustEM  AdjustT
0         East     1            Duke     38.90     65.3
1         West     1         Arizona     37.66     69.8
2      Midwest     1        Michigan     37.59     70.9
3        South     1         Florida     33.79     70.5
4        South     2         Houston     33.43     63.3
5      Midwest     2      Iowa State     32.42     66.5
6        South     3        Illinois     32.10     65.5
7         West     2          Purdue     31.20     64.4
8         East     3     Michigan St     28.31     66.0
9         West     3         Gonzaga     28.10     68.6
10        East     2           UConn     27.87     64.4
11       South     5      Vanderbilt     27.51     68.8
12     Midwest     3        Virginia     26.71     65.7
13       South     4        Nebraska     26.16     66.7
14        West     4        Arkansas     26.05     71.0
15     Midwest     6       Tennessee     26.02     65.0
16        East     5       St John's     25.91     69.6
17     Midwest     4         Alabama     25.72     73.1
18        East     6      Louisville     25.42     69.6
19     Midwest     5      Texas Tech     25.22     66.2
20        East     4          Kansas     24.44     67.6
21        West     5       Wisconsin     23.39     68.7
22        West     6             BYU     23.25     69.9
23       South     7    Saint Mary's     23.07     65.2
24       South     9            Iowa     22.44     63.0
25        East     8      Ohio State     22.24     66.1
26        East     7            UCLA     21.67     64.6
27     Midwest     7        Kentucky     21.48     68.3
28       South     6  North Carolina     20.84     67.9
29        West     9      Utah State     20.76     67.7
30        West     7           Miami     20.68     67.6
31     Midwest     8         Georgia     20.48     71.4
32        West     8       Villanova     19.97     65.2
33     Midwest    10     Santa Clara     19.40     69.2
34       South     8         Clemson     19.24     64.2
35        West    11        TEX/NCSU     19.03     66.9
36       South    10       Texas A&M     18.67     70.5
37     Midwest     9     Saint Louis     18.32     71.0
38     Midwest    11        M-OH/SMU     18.09     68.5
39        East     9             TCU     17.59     67.7
40       South    11             VCU     17.21     68.5
41        East    11   South Florida     16.39     71.5
42        West    10        Missouri     15.39     66.2
43        East    10             UCF     15.04     69.2
44     Midwest    12           Akron     12.80     70.3
45       South    12         McNeese     12.48     66.2
46        East    12   Northern Iowa     11.81     62.3
47     Midwest    13         Hofstra      9.49     64.7
48        West    12      High Point      8.40     69.9
49        East    13      CA Baptist      5.99     65.8
50        West    13         Hawai'i      5.97     69.7
51        East    14     N Dakota St      5.13     66.3
52     Midwest    14       Wright St      2.04     67.2
53       South    13            Troy      1.72     64.9
54       South    15           Idaho      1.53     67.7
55       South    14            Penn      1.47     69.0
56        West    14     Kennesaw St      0.57     71.2
57        West    15          Queens     -1.44     69.6
58     Midwest    16        UMBC/HOW     -1.67     66.2
59     Midwest    15    Tennessee St     -1.83     70.2
60        East    15          Furman     -1.98     65.9
61        East    16           Siena     -2.10     64.6
62        West    16     Long Island     -3.95     67.8
63       South    16          PV/LEH    -10.37     66.9

In [75]:
simple.shape

(64, 5)

In [76]:
simple.to_csv(DATA_FILENAME.format(gender="mens"), index=False)

# Add Torvik to Womens

In [77]:
kenpom = pd.read_csv(TORVIK_FILE.format(gender="womens"))
team_info = pd.read_csv(DATA_FILENAME.format(gender="womens"))

In [78]:
kenpom.head()

             Team  Seed     pyth
0     Connecticut     1  0.99961
1            UCLA     1  0.99912
2           Texas     1  0.99883
3  South Carolina     1  0.99864
4             LSU     2  0.99775

In [79]:
team_info.head()

      team_name  region_id  seed team_region
0     Fairfield          1    11  Regional 1
1    High Point          1    15  Regional 1
2       Vermont          4    14  Regional 3
3  UC San Diego          2    14  Regional 4
4      MOST/SFA          4    16  Regional 3

In [80]:
# Match Kenpom and ESPN team names
kenpom['team_name'] = np.nan
choices = team_info['team_name'].tolist()  # Get all of the ESPN team names
for index, row in kenpom.iterrows():
    team = row['Team']
    match = process.extractOne(team, choices)  # extract the best match for every kenpom name
    if match[1] == 100:  # it's a perfect match
        espn_name = team_info[team_info['team_name'] == match[0]]['team_name'].values[0]
        kenpom.loc[index, 'team_name'] = espn_name
        choices.remove(match[0])  # remove that team as a possible choice

# Need to do this first, otherwise the >80 match ¯\_(ツ)_/¯
kenpom.loc[kenpom['Team'] == "Ohio St.", 'team_name'] = "Ohio State"
choices.remove("Ohio State")
kenpom.loc[kenpom['Team'] == "Mississippi", 'team_name'] = "Ole Miss"
choices.remove("Ole Miss")
# kenpom.loc[kenpom['Team'] == "N.C. State", 'team_name'] = 'North Carolina State'
# # choices.remove("North Carolina State")
kenpom.loc[kenpom['Team'] == 'Iowa St.', 'team_name'] = 'Iowa State'
choices.remove('Iowa State')
# kenpom.loc[kenpom['Team'] == 'North Dakota St.', 'team_name'] = 'N Dakota St'
# choices.remove('N Dakota St')

scores = {}
for index, row in kenpom[kenpom['team_name'].isna()].iterrows():
    team = row['Team']
    match = process.extractOne(team, choices)
    espn_name = team_info[team_info['team_name'] == match[0]]['team_name'].values[0]
    scores[team] = match, espn_name
    if match[1] > 80:
        kenpom.loc[index, 'team_name'] = espn_name
        choices.remove(match[0])  # remove that team as a possible choice

missing_kenpom = kenpom.loc[kenpom['team_name'].isna(), 'Team'].tolist()
missing_espn = team_info.loc[team_info['team_name'].isin(choices)][['team_name']]

print("Missing Kenpom Teams: {}".format(missing_kenpom))
print("Matching ESPN Teams:\n {}".format(missing_espn))

Missing Kenpom Teams: ['Connecticut', 'Nebraska', 'Virginia', 'Richmond', 'Arizona St.', 'Missouri St.', 'Fairleigh Dickinson', 'Stephen F. Austin', 'Southern', 'Samford']
Matching ESPN Teams:
    team_name
4   MOST/SFA
7    SOU/SAM
16     UConn
20       FDU
41  NEB/RICH
59   UVA/ASU

In [81]:
scores

{'Connecticut': (('UConn', 72), 'UConn'),
 'N.C. State': (('NC State', 89), 'NC State'),
 'Nebraska': (('NEB/RICH', 50), 'NEB/RICH'),
 'Virginia': (('W Illinois', 44), 'W Illinois'),
 'Richmond': (('NEB/RICH', 50), 'NEB/RICH'),
 'Arizona St.': (('S Dakota St', 57), 'S Dakota St'),
 'South Dakota St.': (('S Dakota St', 86), 'S Dakota St'),
 'Western Illinois': (('W Illinois', 86), 'W Illinois'),
 'Cal Baptist': (('CA Baptist', 95), 'CA Baptist'),
 'Missouri St.': (('SOU/SAM', 64), 'SOU/SAM'),
 'Fairleigh Dickinson': (('MOST/SFA', 43), 'MOST/SFA'),
 'Stephen F. Austin': (('MOST/SFA', 43), 'MOST/SFA'),
 'Southern': (('SOU/SAM', 40), 'SOU/SAM'),
 'Samford': (('SOU/SAM', 54), 'SOU/SAM')}

In [82]:
# Need to manually fix the crappy ones
# (kenpom_name, espn_name)
manual_matches = [
    ('Connecticut', 'UConn'),
    ('Fairleigh Dickinson', 'FDU'),
    # TEMP
    ('Nebraska', 'NEB/RICH'),
    ('Samford', 'SOU/SAM'),
    ('Missouri St.', 'MOST/SFA'),
    ('Virginia', 'UVA/ASU'),
]
for team, team_id in manual_matches:
    kenpom.loc[kenpom['Team'] == team, 'team_name'] = team_id

merged = kenpom.merge(team_info, left_on=['team_name', 'Seed'], right_on=['team_name', 'seed'])

simple = merged[['team_region', 'Seed', 'team_name', 'pyth']]

In [83]:
simple

   team_region  Seed       team_name      pyth
0   Regional 1     1           UConn  0.999610
1   Regional 2     1            UCLA  0.999120
2   Regional 3     1           Texas  0.998830
3   Regional 4     1  South Carolina  0.998640
4   Regional 2     2             LSU  0.997750
5   Regional 3     2        Michigan  0.995260
6   Regional 2     3            Duke  0.993670
7   Regional 2     4       Minnesota  0.991480
8   Regional 4     2            Iowa  0.990790
9   Regional 1     2      Vanderbilt  0.990610
10  Regional 3     3      Louisville  0.990411
11  Regional 1     5        Maryland  0.989312
12  Regional 1     3      Ohio State  0.989213
13  Regional 4     4        Oklahoma  0.988614
14  Regional 4     3             TCU  0.988515
15  Regional 3     4   West Virginia  0.988316
16  Regional 3     5        Kentucky  0.988117
17  Regional 1     4  North Carolina  0.986518
18  Regional 4     6      Washington  0.983319
19  Regional 4     9             USC  0.982420
20  Regional 2     5        Ole Miss  0.982121
21  Regional 4     5     Michigan St  0.981722
22  Regional 1     6      Notre Dame  0.980423
23  Regional 3    10       Tennessee  0.979924
24  Regional 3     7        NC State  0.976625
25  Regional 2    11        NEB/RICH  0.975126
26  Regional 2    10       Villanova  0.974627
27  Regional 3     8          Oregon  0.974128
28  Regional 3     6         Alabama  0.972029
29  Regional 2     7      Texas Tech  0.971730
30  Regional 1     7        Illinois  0.971031
31  Regional 4     7         Georgia  0.971032
32  Regional 2     8     Oklahoma St  0.967133
33  Regional 1     8      Iowa State  0.966634
34  Regional 2     6          Baylor  0.963835
35  Regional 1    10        Colorado  0.961536
36  Regional 3     9   Virginia Tech  0.958937
37  Regional 1     9        Syracuse  0.950139
38  Regional 4    10         UVA/ASU  0.943740
39  Regional 3    12   James Madison  0.937543
40  Regional 4     8         Clemson  0.921749
41  Regional 2     9       Princeton  0.920450
42  Regional 4    11     S Dakota St  0.918852
43  Regional 3    11    Rhode Island  0.891458
44  Regional 1    11       Fairfield  0.890759
45  Regional 2    12         Gonzaga  0.885062
46  Regional 4    12     Colorado St  0.856670
47  Regional 3    13        Miami OH  0.841972
48  Regional 2    13       Green Bay  0.787088
49  Regional 4    13           Idaho  0.786089
50  Regional 3    14         Vermont  0.766094
51  Regional 1    12       Murray St  0.743310
52  Regional 1    13      W Illinois  0.724011
53  Regional 4    14    UC San Diego  0.684411
54  Regional 2    16      CA Baptist  0.681811
55  Regional 2    14      Charleston  0.648312
56  Regional 1    16            UTSA  0.643513
57  Regional 3    16        MOST/SFA  0.621313
58  Regional 4    15             FDU  0.620613
59  Regional 2    15    Jacksonville  0.572215
60  Regional 3    15      Holy Cross  0.515716
61  Regional 1    15      High Point  0.508517
62  Regional 1    14          Howard  0.463418
63  Regional 4    16         SOU/SAM  0.195327

In [84]:
simple.to_csv(DATA_FILENAME.format(gender="womens"), index=False)

## OLD

In [27]:
# espn = pd.read_csv(ESPN_FILE)
# GENDERS = ["mens", "womens"]
# forecast_dates = espn.groupby(
#     ["gender", "forecast_date", "results_to"]
# ).filter(lambda x: len(x) == 64).groupby("gender")["forecast_date"].unique().to_dict()
# print(forecast_dates)
# results = {}
# for gender in GENDERS:
#     forecast_date = forecast_dates[gender]
#     assert len(forecast_date) == 1
#     espn_slice = (
#         (espn['gender'] == gender) &
#         (espn['forecast_date'] == forecast_date[0]) &
#         (espn["team_alive"] == 1) 
#     )
#     # For backdated runs
#     # espn_slice = (espn['gender'] == 'mens') & (espn['forecast_date'] == "2023-03-15") & (espn["team_alive"] == 1)
#     simple = espn[espn_slice][['team_region', 'team_seed', 'team_name', 'team_id', 'team_rating']].rename(columns={"team_seed": "Seed"})
#     simple["Seed"] = simple["Seed"].str.replace("\D", "", regex=True)
#     results[gender] = simple