In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from bracket_functions import create_initial_bracket, JSONEncoder, save_brackets
from bracket_predictions import sequential_predictions, parallel_predictions
from constants import DATA_FILENAME, BRACKETS_JSON, BRACKETS_DIRECTORY, ORDER_OF_REGIONS, DATA_DIRECTORY
import json
import pandas as pd

In [3]:
pd.options.display.max_rows = 999

In [4]:
GENDER = "womens"

In [5]:
initial_bracket, data = create_initial_bracket(DATA_FILENAME.format(gender=GENDER), ORDER_OF_REGIONS[GENDER])

In [6]:
# 2023, 2024 values
sd_params = (11, 0)
k = 0

# 2022 values
# sd_params = (12, 1.9)
# k = 0

# 2021 values
# sd_params = (11, 0)
# sd_params = (10, -0.21)
# k = 0

In [7]:
%%time
bracket_dict = sequential_predictions(11, initial_bracket, data, sd_params, k, score_method="538")
# bracket_dict = sequential_predictions(11, initial_bracket, data, sd_params, k, score_method="kenpom")

CPU times: user 560 ms, sys: 20.8 ms, total: 580 ms
Wall time: 565 ms

In [8]:
# bracket_name = 'bracket8'
for bracket in range(0, 11):
    bracket_name = f'bracket{bracket}'
    bracket = bracket_dict[bracket_name][0]
    display(bracket.loc[bracket['8'] != ''][["Region", "Seed", "8", "4", "2", "1"]])

          Region  Seed               8        4        2     1
0      Spokane 1     1            UCLA     UCLA     UCLA  UCLA
14     Spokane 1     2        NC State
16     Spokane 4     1             USC      USC
30     Spokane 4     2           UConn
36  Birmingham 2     5         Alabama  Alabama  Alabama
42  Birmingham 2     3  North Carolina
48  Birmingham 3     1           Texas    Texas
56  Birmingham 3     6        Michigan

          Region  Seed           8           4     2     1
6      Spokane 1     4      Baylor
10     Spokane 1     3         LSU         LSU   LSU
16     Spokane 4     1         USC         USC
30     Spokane 4     2       UConn
35  Birmingham 2     9     Indiana
46  Birmingham 2     2        Duke        Duke  Duke  Duke
48  Birmingham 3     1       Texas
58  Birmingham 3     3  Notre Dame  Notre Dame

          Region  Seed           8           4           2           1
0      Spokane 1     1        UCLA        UCLA
14     Spokane 1     2    NC State
16     Spokane 4     1         USC         USC         USC
24     Spokane 4     6        Iowa
34  Birmingham 2     8        Utah
46  Birmingham 2     2        Duke        Duke
48  Birmingham 3     1       Texas
58  Birmingham 3     3  Notre Dame  Notre Dame  Notre Dame  Notre Dame

          Region  Seed               8               4               2      1
6      Spokane 1     4          Baylor
10     Spokane 1     3             LSU             LSU
16     Spokane 4     1             USC
30     Spokane 4     2           UConn           UConn           UConn  UConn
32  Birmingham 2     1  South Carolina  South Carolina  South Carolina
40  Birmingham 2     6   West Virginia
48  Birmingham 3     1           Texas
58  Birmingham 3     3      Notre Dame      Notre Dame

          Region  Seed               8               4               2      1
0      Spokane 1     1            UCLA
14     Spokane 1     2        NC State        NC State
22     Spokane 4     4        Kentucky
30     Spokane 4     2           UConn           UConn           UConn  UConn
32  Birmingham 2     1  South Carolina  South Carolina  South Carolina
40  Birmingham 2     6   West Virginia
48  Birmingham 3     1           Texas           Texas
58  Birmingham 3     3      Notre Dame

          Region  Seed               8               4      2      1
4      Spokane 1     5        Ole Miss
14     Spokane 1     2        NC State        NC State
22     Spokane 4     4        Kentucky
30     Spokane 4     2           UConn           UConn  UConn
32  Birmingham 2     1  South Carolina  South Carolina
42  Birmingham 2     3  North Carolina
48  Birmingham 3     1           Texas           Texas  Texas  Texas
58  Birmingham 3     3      Notre Dame

          Region  Seed               8           4           2      1
0      Spokane 1     1            UCLA        UCLA
14     Spokane 1     2        NC State
20     Spokane 4     5      Kansas St.  Kansas St.  Kansas St.
24     Spokane 4     6            Iowa
32  Birmingham 2     1  South Carolina
46  Birmingham 2     2            Duke        Duke
48  Birmingham 3     1           Texas       Texas       Texas  Texas
58  Birmingham 3     3      Notre Dame

          Region  Seed               8               4               2      1
0      Spokane 1     1            UCLA            UCLA
14     Spokane 1     2        NC State
16     Spokane 4     1             USC
30     Spokane 4     2           UConn           UConn           UConn  UConn
32  Birmingham 2     1  South Carolina  South Carolina  South Carolina
46  Birmingham 2     2            Duke
48  Birmingham 3     1           Texas
58  Birmingham 3     3      Notre Dame      Notre Dame

          Region  Seed               8              4      2      1
0      Spokane 1     1            UCLA
10     Spokane 1     3             LSU            LSU
16     Spokane 4     1             USC
30     Spokane 4     2           UConn          UConn  UConn  UConn
32  Birmingham 2     1  South Carolina
40  Birmingham 2     6   West Virginia  West Virginia
48  Birmingham 3     1           Texas          Texas  Texas
62  Birmingham 3     2             TCU

,Region,Seed,8,4,2,1
4,Spokane 1,5,Ole Miss,,,
8,Spokane 1,6,Florida St.,Florida St.,,
20,Spokane 4,5,Kansas St.,,,
30,Spokane 4,2,UConn,UConn,UConn,
32,Birmingham 2,1,South Carolina,South Carolina,South Carolina,South Carolina
40,Birmingham 2,6,West Virginia,,,
51,Birmingham 3,9,Creighton,,,
58,Birmingham 3,3,Notre Dame,Notre Dame,,

          Region  Seed               8               4      2      1
2      Spokane 1     8        Richmond
8      Spokane 1     6     Florida St.     Florida St.
16     Spokane 4     1             USC             USC    USC
24     Spokane 4     6            Iowa
32  Birmingham 2     1  South Carolina  South Carolina
40  Birmingham 2     6   West Virginia
48  Birmingham 3     1           Texas           Texas  Texas  Texas
62  Birmingham 3     2             TCU

## Initial Submissions

In [9]:
EXPORT_JSON = f"{DATA_DIRECTORY}/brackets_submit.json".format(gender=GENDER)
EXPORT_DIRECTORY = f"{DATA_DIRECTORY}/brackets_submit/".format(gender=GENDER)

In [10]:
%%time
with open(EXPORT_JSON, 'w') as fp:
    json.dump(bracket_dict, fp, sort_keys=True, indent=4, cls=JSONEncoder)

CPU times: user 3.77 ms, sys: 2.72 ms, total: 6.5 ms
Wall time: 26.1 ms

In [11]:
save_brackets(EXPORT_JSON, EXPORT_DIRECTORY, 'all', [f'bracket{i}' for i in range(10)])

## Prod Runs

In [12]:
%%time
# NUM_BRACKETS = 100
NUM_BRACKETS = 1000000
for gender in ["mens", "womens"]:
    initial_bracket, data = create_initial_bracket(DATA_FILENAME.format(gender=gender), ORDER_OF_REGIONS[gender])
    bracket_dict = parallel_predictions(NUM_BRACKETS, initial_bracket, data, sd_params, k, score_method="538")
    with open(BRACKETS_JSON.format(gender=gender), 'w') as fp:
        json.dump(bracket_dict, fp, sort_keys=True, indent=4, cls=JSONEncoder)

CPU times: user 1h 10min 37s, sys: 3min, total: 1h 13min 38s
Wall time: 2h 47min 10s

In [12]:
%%time
gender = "mens"
initial_bracket, data = create_initial_bracket(DATA_FILENAME.format(gender=gender), ORDER_OF_REGIONS[gender])
bracket_dict = parallel_predictions(1000000, initial_bracket, data, sd_params, k, score_method="kenpom")

with open(f"{DATA_DIRECTORY.format(gender='mens')}/brackets_kenpom.json", 'w') as fp:
    json.dump(bracket_dict, fp, sort_keys=True, indent=4, cls=JSONEncoder)

CPU times: user 37min 38s, sys: 1min 16s, total: 38min 54s
Wall time: 4h 1s

In [9]:
%%time
with open(f"{DATA_DIRECTORY}/brackets_2022_538.json", 'w') as fp:
    json.dump(bracket_dict, fp, sort_keys=True, indent=4, cls=JSONEncoder)

CPU times: user 15min 52s, sys: 32.7 s, total: 16min 25s
Wall time: 16min 26s

In [9]:
%%time
with open(f"{DATA_DIRECTORY}/brackets_2022_12_1.9.json", 'w') as fp:
    json.dump(bracket_dict, fp, sort_keys=True, indent=4, cls=JSONEncoder)

CPU times: user 16min, sys: 33 s, total: 16min 33s
Wall time: 16min 36s

In [10]:
%%time
with open(f"{DATA_DIRECTORY}/brackets_2022_11.json", 'w') as fp:
    json.dump(bracket_dict, fp, sort_keys=True, indent=4, cls=JSONEncoder)

CPU times: user 15min 7s, sys: 35.9 s, total: 15min 43s
Wall time: 15min 44s